# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/VRland',
                'doc_host': 'https://FerranC96.github.io',
                'git_url': 'https://github.com/FerranC96/VRland',
                'lib_path': 'VRland'},
  'syms': { 'VRland.app': {'VRland.app.foo': ('vrland_app.html#foo', 'VRland/app.py')},
            'VRland.land': {'VRland.land.foo': ('landscape.html#foo', 'VRland/land.py')},
            'VRland.score': { 'VRland.score.bycluster_median': ('score.html#bycluster_median', 'VRland/score.py'),
                              'VRland.score.check_inversevvl': ('score.html#check_inversevvl', 'VRland/score.py'),
                              'VRland.score.compute_distdeg': ('score.html#compute_distdeg', 'VRland/score.py'),
                              'VRland.score.compute_vr_scores': ('score.html#compute_vr_scores', 'VRland/score.py'),
                              'VRland.score.foo': ('score.html#foo', 'VRland/score.py'),
                              'VRland.score.scale_metrics': ('score.html#scale_metrics', 'VRland/score.py')}}}
