# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/VRland',
                'doc_host': 'https://FerranC96.github.io',
                'git_url': 'https://github.com/FerranC96/VRland',
                'lib_path': 'vrland'},
  'syms': { 'vrland.app': {'vrland.app.foo': ('vrland_app.html#foo', 'vrland/app.py')},
            'vrland.land': { 'vrland.land.foo': ('landscape.html#foo', 'vrland/land.py'),
                             'vrland.land.generate_grid': ('landscape.html#generate_grid', 'vrland/land.py'),
                             'vrland.land.interpolate_landscape': ('landscape.html#interpolate_landscape', 'vrland/land.py')},
            'vrland.score': { 'vrland.score.bycluster_median': ('score.html#bycluster_median', 'vrland/score.py'),
                              'vrland.score.check_inversevvl': ('score.html#check_inversevvl', 'vrland/score.py'),
                              'vrland.score.compute_distdeg': ('score.html#compute_distdeg', 'vrland/score.py'),
                              'vrland.score.compute_vr_scores': ('score.html#compute_vr_scores', 'vrland/score.py'),
                              'vrland.score.scale_metrics': ('score.html#scale_metrics', 'vrland/score.py')}}}
