# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/VRland',
                'doc_host': 'https://FerranC96.github.io',
                'git_url': 'https://github.com/FerranC96/VRland',
                'lib_path': 'VRland'},
  'syms': { 'VRland.core': { 'VRland.core.foo': ('core.html#foo', 'VRland/core.py'),
                             'VRland.core.say_hi': ('core.html#say_hi', 'VRland/core.py')}}}