# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_VRland_app.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/02_VRland_app.ipynb 3
#| export




# %% ../nbs/02_VRland_app.ipynb 6
def foo(): pass
