# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_app_vrland.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/03_app_vrland.ipynb 3
#| export




# %% ../nbs/03_app_vrland.ipynb 6
def foo(): pass
