# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_VRland_app.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/02_VRland_app.ipynb 4
#| export


# %% ../nbs/02_VRland_app.ipynb 7
def foo(): pass
