# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hi', 'foo']

# %% ../nbs/00_core.ipynb 3
def say_hi(to):
    "Salute someone"
    return f"Hi {to}!"

# %% ../nbs/00_core.ipynb 4
def foo(): pass
